# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: ":chatgpt-note"
    replace: |
      Remember to follow best practices for writing a Note for my Obsidian Vault:
      - Avoid being redundant, sometimes you discuss the same aspect twice
      - Avoid obvious technical facts (i.e. the trade-off between latency and throughput) but feel free to provide complex technical insights,
      as well as code examples if applicable. Feel also free to expand on the root cause (i.e. why it is unfeasible to invert a scalar product on an elliptic curve? And you explain about scalar products, sum on an elliptic curve, etc)
      - Avoid using styles for headers. Avoid a title, Obsidian will assign one. Starts paragraphs from H2/##
      - Avoid using Math formulas with \ . Obsidian supports the $$ syntax. Try to use UTF characters for simple expressions (dot product?)
      - Use paragraph to organize the thoughts into self-contained sections, and use titles with headers.
      - Avoid bullet point lists except for finite sets (i.e. days of the week)

  # And much more! For more information, visit the docs: https://espanso.org/docs/

