local ai = require("custom.plugins.dev.ai")
local dap = require("custom.plugins.dev.dap")
local langs = require("custom.plugins.dev.langs")
local lsp = require("custom.plugins.dev.lsp")
local parsing = require("custom.plugins.dev.parsing")
local productivity = require("custom.plugins.dev.productivity")
local remoting = require("custom.plugins.dev.productivity")
local snippets = require("custom.plugins.dev.snippets")

return vim.tbl_deep_extend("force", ai, dap, langs, lsp, parsing, productivity, remoting, snippets)
